import type { CourseCatalog } from "@/types/course";

export const mockCourseCatalog: CourseCatalog = {
  featuredCourse: {
    id: "course-next-ai-lms",
    slug: "nextjs-ai-lms-foundation",
    title: "Next.js로 시작하는 AI LMS 프론트엔드",
    subtitle: "강의 탐색, 상세, 수강 흐름을 실제 제품 구조로 설계합니다.",
    description:
      "마케팅 페이지가 아니라 실제 서비스 화면을 기준으로 App Router, 인증, 강의 목록, 상세, 수강 플레이어까지 이어지는 기반을 만듭니다.",
    category: "프론트엔드",
    tags: ["Next.js", "TypeScript", "App Router"],
    level: "중급",
    durationLabel: "18시간 20분",
    lessonCount: 42,
    priceLabel: "월 구독 포함",
    rating: 4.9,
    reviewCount: 182,
    enrollmentCount: 1240,
    thumbnailTone: "from-[#10302b] via-[#145c54] to-[#d7f3eb]",
    instructor: {
      name: "민수 김",
      title: "Frontend Engineer",
    },
    enrollmentStatus: "ACTIVE",
    isFeatured: true,
    learningPoints: [
      "App Router 기반 서비스 화면 구조를 실제 LMS 흐름에 맞춰 설계합니다.",
      "강의 목록, 상세, 플레이어 접근 정책을 프론트 기준으로 연결합니다.",
      "인증 저장소와 API 계층을 제품 구조에 맞게 분리합니다.",
      "AI 보조 패널을 붙이기 좋은 플레이어 레이아웃 기준을 잡습니다.",
    ],
    curriculumPreview: [
      {
        id: "lesson-next-1",
        title: "서비스형 LMS 정보 구조 잡기",
        durationLabel: "18분",
        isPreview: true,
        summary: "학생, 강사, 관리자 흐름을 한 서비스 안에서 어떻게 나눌지 먼저 정의합니다.",
        headers: ["사용자 역할", "라우트 구조", "핵심 화면"],
      },
      {
        id: "lesson-next-2",
        title: "App Router로 라우트 그룹 나누기",
        durationLabel: "26분",
        summary: "마케팅, 인증, 플랫폼 영역을 라우트 그룹으로 분리하는 기준을 다룹니다.",
        headers: ["Route Group", "Layout", "Navigation"],
      },
      {
        id: "lesson-next-3",
        title: "강의 목록과 상세 데이터 모델 정리",
        durationLabel: "32분",
        summary: "카탈로그, 상세, 플레이어 응답을 분리하는 데이터 구조를 잡습니다.",
        headers: ["Catalog DTO", "Detail DTO", "Enrollment Status"],
      },
      {
        id: "lesson-next-4",
        title: "수강 상태와 플레이어 접근 제어 연결",
        durationLabel: "24분",
        summary: "ACTIVE 상태만 플레이어로 진입시키고 나머지는 안내하는 흐름을 정리합니다.",
        headers: ["권한 체크", "403 UX", "CTA 제어"],
      },
    ],
  },
  categories: [
    "전체",
    "프론트엔드",
    "백엔드",
    "AI 활용",
    "데이터",
    "디자인 시스템",
  ],
  courses: [
    {
      id: "course-react-state",
      slug: "react-state-patterns",
      title: "React 상태 설계 패턴",
      subtitle: "UI 상태와 서버 상태를 분리해서 다루는 실전 패턴",
      description:
        "Zustand, 서버 상태, 폼 상태를 분리해 유지보수 가능한 대시보드와 학습 제품 UI를 설계합니다.",
      category: "프론트엔드",
      tags: ["React", "Zustand", "Architecture"],
      level: "중급",
      durationLabel: "9시간 40분",
      lessonCount: 27,
      priceLabel: "₩69,000",
      rating: 4.8,
      reviewCount: 96,
      enrollmentCount: 860,
      thumbnailTone: "from-[#1e293b] via-[#334155] to-[#cbd5e1]",
      instructor: {
        name: "정하늘",
        title: "Senior Frontend Developer",
      },
      enrollmentStatus: "NOT_ENROLLED",
      learningPoints: [
        "서버 상태와 UI 상태를 분리하는 기준을 익힙니다.",
        "Zustand와 폼 상태를 섞지 않는 구조를 배웁니다.",
        "복잡한 대시보드 화면에서 상태 책임을 나누는 법을 다룹니다.",
      ],
      curriculumPreview: [
        {
          id: "lesson-react-1",
          title: "로컬 상태와 서버 상태 경계 설정",
          durationLabel: "21분",
          isPreview: true,
          summary: "UI 상태와 서버 상태를 섞지 않기 위한 최소한의 경계를 먼저 세웁니다.",
          headers: ["UI State", "Server State", "Form State"],
        },
        {
          id: "lesson-react-2",
          title: "전역 스토어 설계 실수 피하기",
          durationLabel: "19분",
          summary: "전역 상태가 비대해지는 시점을 피하고 필요한 책임만 남깁니다.",
          headers: ["Zustand", "Selector", "Persist"],
        },
        {
          id: "lesson-react-3",
          title: "대시보드 UI 상태 모듈화",
          durationLabel: "23분",
          summary: "복잡한 학습 대시보드 화면을 기능 단위 상태로 분해합니다.",
          headers: ["Dashboard", "Feature Split", "Component State"],
        },
      ],
    },
    {
      id: "course-spring-lms-api",
      slug: "spring-lms-api-design",
      title: "Spring으로 만드는 LMS API 설계",
      subtitle: "강의, 수강, 진도, 권한 모델링을 한 번에 정리",
      description:
        "강의 목록 API와 수강 플레이어 API를 분리하고 권한 체크를 안정적으로 설계하는 방법을 다룹니다.",
      category: "백엔드",
      tags: ["Spring", "JPA", "Authorization"],
      level: "중급",
      durationLabel: "14시간 10분",
      lessonCount: 35,
      priceLabel: "₩89,000",
      rating: 4.7,
      reviewCount: 73,
      enrollmentCount: 670,
      thumbnailTone: "from-[#2e1065] via-[#6d28d9] to-[#ede9fe]",
      instructor: {
        name: "이도현",
        title: "Backend Architect",
      },
      enrollmentStatus: "PENDING",
      learningPoints: [
        "LMS 도메인에서 강의/수강/진도 모델을 분리합니다.",
        "목록 API와 플레이어 API를 분리해 설계하는 이유를 이해합니다.",
        "권한 체크를 프론트와 백엔드에서 동시에 다루는 방식을 정리합니다.",
      ],
      curriculumPreview: [
        {
          id: "lesson-spring-1",
          title: "수강 상태 모델과 권한 매트릭스",
          durationLabel: "28분",
          isPreview: true,
          summary: "학생이 어떤 상태에서 어떤 API에 접근 가능한지 권한 매트릭스로 정리합니다.",
          headers: ["Enrollment", "Authorization", "Matrix"],
        },
        {
          id: "lesson-spring-2",
          title: "강의 상세 응답과 플레이어 응답 분리",
          durationLabel: "31분",
          summary: "상세 응답과 플레이어 응답을 분리하는 이유와 장단점을 설명합니다.",
          headers: ["Detail API", "Player API", "Response Shape"],
        },
        {
          id: "lesson-spring-3",
          title: "403 처리와 클라이언트 UX 설계",
          durationLabel: "17분",
          summary: "서버 403을 기준으로 프런트의 안내 흐름을 설계합니다.",
          headers: ["403", "Fallback", "User Guidance"],
        },
      ],
    },
    {
      id: "course-llm-study-assistant",
      slug: "llm-study-assistant-ui",
      title: "LLM 학습 도우미 UI 설계",
      subtitle: "AI를 수강 흐름 안에 자연스럽게 붙이는 방법",
      description:
        "요약, 쉬운 설명, 예상 문제 생성 기능을 플레이어 맥락에 맞게 보조 패널로 설계합니다.",
      category: "AI 활용",
      tags: ["LLM", "Prompt UX", "Education"],
      level: "입문",
      durationLabel: "7시간 25분",
      lessonCount: 18,
      priceLabel: "₩59,000",
      rating: 4.9,
      reviewCount: 121,
      enrollmentCount: 1130,
      thumbnailTone: "from-[#3f6212] via-[#84cc16] to-[#ecfccb]",
      instructor: {
        name: "박서윤",
        title: "AI Product Designer",
      },
      enrollmentStatus: "ACTIVE",
      learningPoints: [
        "AI 기능을 메인 학습 흐름을 방해하지 않게 배치합니다.",
        "요약, 쉬운 설명, 퀴즈 생성 UI를 플레이어 맥락에 맞춰 설계합니다.",
        "학생이 다시 질문하기 쉬운 인터랙션 패턴을 만듭니다.",
      ],
      curriculumPreview: [
        {
          id: "lesson-llm-1",
          title: "보조 패널형 AI UX의 기본 원칙",
          durationLabel: "15분",
          isPreview: true,
          summary: "AI를 메인 플레이어를 방해하지 않는 보조 패널로 배치하는 원칙을 다룹니다.",
          headers: ["Panel UX", "Context", "Prompt Entry"],
        },
        {
          id: "lesson-llm-2",
          title: "학습 요약 카드와 후속 질문 흐름",
          durationLabel: "22분",
          summary: "요약 카드에서 후속 질문으로 자연스럽게 이어지는 인터랙션을 설계합니다.",
          headers: ["Summary", "Follow-up", "Question Flow"],
        },
        {
          id: "lesson-llm-3",
          title: "예상 문제 생성 인터페이스",
          durationLabel: "20분",
          summary: "퀴즈 생성 UI가 학습 복습 흐름 안에서 어떻게 보여야 하는지 다룹니다.",
          headers: ["Quiz", "Review", "Interaction"],
        },
      ],
    },
    {
      id: "course-sql-learning-analytics",
      slug: "sql-learning-analytics",
      title: "SQL로 보는 학습 분석",
      subtitle: "학생 위험도와 이탈 신호를 데이터로 읽는 법",
      description:
        "LMS 로그를 기반으로 학습 진도, 과제 제출, 재생 패턴을 조회하는 분석 쿼리를 설계합니다.",
      category: "데이터",
      tags: ["SQL", "Analytics", "BI"],
      level: "입문",
      durationLabel: "6시간 50분",
      lessonCount: 21,
      priceLabel: "₩49,000",
      rating: 4.6,
      reviewCount: 58,
      enrollmentCount: 430,
      thumbnailTone: "from-[#083344] via-[#0891b2] to-[#cffafe]",
      instructor: {
        name: "한지민",
        title: "Data Analyst",
      },
      enrollmentStatus: "COMPLETED",
      learningPoints: [
        "학습 로그를 기반으로 주요 지표를 읽는 방법을 배웁니다.",
        "위험 학생 탐지를 위한 기본 지표 설계를 다룹니다.",
        "BI 관점에서 LMS 데이터를 해석하는 기준을 잡습니다.",
      ],
      curriculumPreview: [
        {
          id: "lesson-sql-1",
          title: "학습 이탈 신호 정의하기",
          durationLabel: "16분",
          isPreview: true,
        },
        {
          id: "lesson-sql-2",
          title: "진도율과 재생 패턴 분석 쿼리",
          durationLabel: "27분",
        },
        {
          id: "lesson-sql-3",
          title: "리스크 학생 세그먼트 만들기",
          durationLabel: "24분",
        },
      ],
    },
    {
      id: "course-design-system-edu",
      slug: "design-system-for-education",
      title: "교육 제품용 디자인 시스템",
      subtitle: "학생과 강사 화면을 공통 토큰으로 정리합니다.",
      description:
        "학습 제품 특유의 카드, 상태 배지, 커리큘럼 패널을 디자인 토큰과 컴포넌트로 추상화합니다.",
      category: "디자인 시스템",
      tags: ["Design System", "Tokens", "Accessibility"],
      level: "중급",
      durationLabel: "11시간 15분",
      lessonCount: 29,
      priceLabel: "₩79,000",
      rating: 4.8,
      reviewCount: 87,
      enrollmentCount: 590,
      thumbnailTone: "from-[#4c0519] via-[#be185d] to-[#fce7f3]",
      instructor: {
        name: "윤태호",
        title: "Product Designer",
      },
      enrollmentStatus: "NOT_ENROLLED",
      learningPoints: [
        "교육 제품에 필요한 상태 카드와 패널 패턴을 정리합니다.",
        "토큰 기반 UI 시스템으로 학생/강사 화면을 일관되게 만듭니다.",
        "재사용 가능한 컴포넌트 경계를 잡는 법을 다룹니다.",
      ],
      curriculumPreview: [
        {
          id: "lesson-ds-1",
          title: "교육 제품의 핵심 UI 토큰",
          durationLabel: "18분",
          isPreview: true,
        },
        {
          id: "lesson-ds-2",
          title: "상태 배지와 카드 컴포넌트 시스템",
          durationLabel: "21분",
        },
        {
          id: "lesson-ds-3",
          title: "강사와 학생 화면의 공통 패턴 추출",
          durationLabel: "25분",
        },
      ],
    },
    {
      id: "course-node-streaming",
      slug: "node-streaming-video-pipeline",
      title: "Node.js 영상 처리 파이프라인",
      subtitle: "업로드부터 인코딩 큐까지 서비스 구조로 배우는 백엔드",
      description:
        "강의 업로드와 재생 준비를 위한 영상 처리 흐름과 작업 큐 구조를 실제 기능 기준으로 정리합니다.",
      category: "백엔드",
      tags: ["Node.js", "Queue", "Media"],
      level: "심화",
      durationLabel: "13시간 30분",
      lessonCount: 31,
      priceLabel: "₩99,000",
      rating: 4.7,
      reviewCount: 64,
      enrollmentCount: 350,
      thumbnailTone: "from-[#111827] via-[#374151] to-[#e5e7eb]",
      instructor: {
        name: "최준영",
        title: "Platform Engineer",
      },
      enrollmentStatus: "NOT_ENROLLED",
      learningPoints: [
        "영상 업로드 이후 처리 파이프라인을 서비스 관점에서 설명합니다.",
        "인코딩 큐와 재생 준비 상태를 백엔드에서 관리하는 흐름을 다룹니다.",
        "미디어 처리 실패 케이스를 운영 관점에서 설계합니다.",
      ],
      curriculumPreview: [
        {
          id: "lesson-node-1",
          title: "업로드 직후 처리 단계 설계",
          durationLabel: "20분",
          isPreview: true,
        },
        {
          id: "lesson-node-2",
          title: "인코딩 큐와 상태 전이 모델",
          durationLabel: "29분",
        },
        {
          id: "lesson-node-3",
          title: "미디어 파이프라인 장애 대응",
          durationLabel: "18분",
        },
      ],
    },
  ],
};
